import {
  CrownIcon,
  GlobeIcon,
  Mail01Icon,
  Calendar01Icon,
  StarIcon,
  MusicNote01Icon,
  Building01Icon,
  Store01Icon,
  ChartBarLineIcon,
  ShoppingBag01Icon,
  File01Icon,
  Video01Icon,
  Camera01Icon,
  HeadphonesIcon,
  Mic01Icon,
  DiscIcon,
  PlayIcon,
  CheckmarkCircle01Icon,
  ArrowRight01Icon,
  Settings01Icon,
  UserIcon,
  Link01Icon,
  Share01Icon,
  Copy01Icon,
  Shield01Icon,
  CreditCardIcon,
  Notification01Icon,
  Search01Icon,
  Edit01Icon,
  Delete01Icon,
  PlusSignIcon,
  Tick01Icon,
  Download01Icon,
  Layers01Icon,
  ComputerIcon,
  SmartPhone01Icon,
} from '@hugeicons/core-free-icons';

export const HUGE_ICONS_REGISTRY = {
  crown: CrownIcon,
  globe: GlobeIcon,
  mail: Mail01Icon,
  calendar: Calendar01Icon,
  star: StarIcon,
  music: MusicNote01Icon,
  building: Building01Icon,
  store: Store01Icon,
  analytics: ChartBarLineIcon,
  shopping: ShoppingBag01Icon,
  file: File01Icon,
  video: Video01Icon,
  camera: Camera01Icon,
  headphones: HeadphonesIcon,
  mic: Mic01Icon,
  disc: DiscIcon,
  play: PlayIcon,
  check: CheckmarkCircle01Icon,
  tick: Tick01Icon,
  arrowRight: ArrowRight01Icon,
  settings: Settings01Icon,
  user: UserIcon,
  link: Link01Icon,
  share: Share01Icon,
  copy: Copy01Icon,
  shield: Shield01Icon,
  creditCard: CreditCardIcon,
  notification: Notification01Icon,
  search: Search01Icon,
  edit: Edit01Icon,
  delete: Delete01Icon,
  plus: PlusSignIcon,
  download: Download01Icon,
  layers: Layers01Icon,
  computer: ComputerIcon,
  mobile: SmartPhone01Icon,
};

export type HugeIconKey = keyof typeof HUGE_ICONS_REGISTRY;

export function getHugeIcon(key: string) {
  return HUGE_ICONS_REGISTRY[key as HugeIconKey] || Link01Icon;
}
