import { UserProfile } from './types';

export const BRAND_LOGOS: Record<string, string> = {
  youtube: 'https://cdn.simpleicons.org/youtube/FF0000',
  spotify: 'https://cdn.simpleicons.org/spotify/1DB954',
  github: 'https://cdn.simpleicons.org/github/181717',
  x: 'https://cdn.simpleicons.org/x/000000',
  twitter: 'https://cdn.simpleicons.org/x/000000',
  instagram: 'https://cdn.simpleicons.org/instagram/E4405F',
  linkedin: 'https://cdn.simpleicons.org/linkedin/0A66C2',
  substack: 'https://cdn.simpleicons.org/substack/FF6719',
  figma: 'https://cdn.simpleicons.org/figma/F24E1E',
  discord: 'https://cdn.simpleicons.org/discord/5865F2',
  tiktok: 'https://cdn.simpleicons.org/tiktok/000000',
  twitch: 'https://cdn.simpleicons.org/twitch/9146FF',
  calendly: 'https://cdn.simpleicons.org/calendly/006BFF',
  gumroad: 'https://cdn.simpleicons.org/gumroad/000000',
  store: 'https://cdn.simpleicons.org/shopify/7AB55C',
  podcast: 'https://cdn.simpleicons.org/applepodcasts/872EC4',
  web: 'https://cdn.simpleicons.org/safari/000000',
};

// Clean starter default profile reflecting the editorial reference layout
export const DEFAULT_STARTER_PROFILE: UserProfile = {
  id: 'creator_profile',
  username: 'creator',
  name: 'Your Name',
  headline: 'Profile Creator & Host',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
  theme: 'warm',
  socials: {},
  cards: [
    {
      id: 'card-sponsor',
      title: 'Sponsor The Podcast (MB & Audience Stats)',
      subtitle: 'Submit your podcast sponsorship inquiry to our team',
      linkUrl: '#',
      color: 'dark',
      badgeText: '+ Sponsor The Podcast',
      templateType: 'podcast_sponsor_me',
      podcast: {
        monthlyDownloads: '130,000+',
        audienceSize: '122,800s Listeners',
        listenerDemographics: '130.08 KB, Five Podcast, Presisiad & Figineer',
        cpmRate: '16.6K • 21ml • 123.3K • 016',
        pastSponsors: ['Notion', 'Linear', 'Vercel', 'Riverside'],
      },
    },
    {
      id: 'card-collab',
      title: 'Collaborated Pesp Pro',
      subtitle: 'Certified have, 10G package & rack communatats',
      linkUrl: '#',
      color: 'purple',
      badgeText: 'General',
      templateType: 'standard',
    },
    {
      id: 'card-player',
      title: 'Neon Mirage (Official Single)',
      subtitle: 'Sanctent Player • Naonin reneo or dring episode • 5 track name • 20 mins ago',
      linkUrl: '#',
      color: 'dark',
      badgeText: '⚡ PODCAST PREVIEW',
      templateType: 'podcast_latest_episode',
      podcast: {
        episodeTitle: 'Neon Mirage (Official Single)',
        episodeNumber: 'PODCAST PREVIEW',
        duration: '5:58',
        releaseDate: '20 mins ago',
        audioUrl: 'https://actions.google.com/sounds/v1/ambiences/rain_heavy.ogg',
      },
    },
    {
      id: 'card-community',
      title: 'Join Think Shows Premooment?',
      subtitle: 'Conficess newsler and anreis with ibo proo...',
      linkUrl: '#',
      color: 'purple',
      badgeText: 'Community',
      templateType: 'standard',
    },
    {
      id: 'card-stats-1',
      title: 'Creator News & Performance',
      subtitle: 'Last 5 Items by Comicssant Name',
      linkUrl: '#',
      color: 'dark',
      badgeText: 'Analytics',
      templateType: 'podcast_stats',
      podcast: {
        monthlyDownloads: '5.2%',
        audienceSize: '4.2%',
        chartRank: '2.2%',
      },
    },
    {
      id: 'card-trend',
      title: 'Learn Specific Scoring trend, to STOX Add',
      subtitle: 'Learn appssic sosing trend and oerlastiefy experted',
      linkUrl: '#',
      color: 'dark',
      badgeText: '⚡ LOAD AWARNES',
      templateType: 'featured_work',
      featuredWork: {
        title: 'Learn Specific Scoring trend, to STOX Add',
        brandName: 'Market Trend',
        resultsMetric: 'Learn in ontlow',
      },
    },
    {
      id: 'card-stats-2',
      title: '2 Adirans & Engagement dide titles',
      subtitle: 'Verified quarterly reach & audience interaction rates',
      linkUrl: '#',
      color: 'dark',
      badgeText: 'Engagement',
      templateType: 'podcast_stats',
      podcast: {
        monthlyDownloads: '60K',
        audienceSize: '4.8%',
        chartRank: '1.2M',
      },
    },
    {
      id: 'card-booking',
      title: 'Book Market Live Shows & Festivals',
      subtitle: 'Enodk • 1 hour ago • Chok & frns to yours',
      linkUrl: '#',
      color: 'dark',
      badgeText: '⚡ LIVE SHOWS & FESTIVALS',
      templateType: 'music_booking_inquiry',
      music: {
        bookingRate: 'Live Shows & Festivals',
        epkBio: 'Enodk • 1 hour ago • Chok & frns to yours',
      },
    },
    {
      id: 'card-consult',
      title: 'Contact 1:1 Strategy Consult',
      subtitle: 'Bray poo pasts, dart, strategy and greolents',
      linkUrl: '#',
      color: 'purple',
      badgeText: 'Consult',
      templateType: 'standard',
    },
    {
      id: 'card-video',
      title: '17 Podcast Counting Campaign',
      subtitle: '80 N W Naws ST • 11 date • 10 5pm',
      linkUrl: '#',
      color: 'dark',
      badgeText: 'Video Spotlight',
      templateType: 'podcast_youtube',
      podcast: {
        youtubeChannelUrl: 'https://youtube.com',
      },
    },
    {
      id: 'card-tour',
      title: 'The Happy Fall Tour 2021',
      subtitle: 'Live show tour schedule and booking passes',
      linkUrl: '#',
      color: 'dark',
      badgeText: 'Free',
      templateType: 'music_upcoming_shows',
      music: {
        tourDates: [
          { date: 'Bo. H5, 7 tise', city: 'Be Way Tear', venue: '6 now 1 ad 6:00 up', ticketUrl: '#', soldOut: false },
          { date: 'No. H5, 7 tleo', city: 'Think Lasic', venue: '6 to care 6pm', ticketUrl: '#', soldOut: false },
          { date: 'Jan 25, 2023', city: 'Share ago: 1.0B fr', venue: '120 Listenaps', ticketUrl: '#', soldOut: false },
        ],
      },
    },
    {
      id: 'card-directory',
      title: 'Enter the Port Room to Podcast App',
      subtitle: 'Multi-platform streaming and community hubs',
      linkUrl: '#',
      color: 'dark',
      badgeText: 'Directory',
      templateType: 'podcast_listen_on',
    },
  ],
};
